/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.pending_props_pb.Balance', null, global);
goog.exportSymbol('proto.pending_props_pb.BalanceDetails', null, global);
goog.exportSymbol('proto.pending_props_pb.BalanceType', null, global);
goog.exportSymbol('proto.pending_props_pb.UpdateType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pending_props_pb.BalanceDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pending_props_pb.BalanceDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pending_props_pb.BalanceDetails.displayName = 'proto.pending_props_pb.BalanceDetails';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pending_props_pb.BalanceDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.pending_props_pb.BalanceDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pending_props_pb.BalanceDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pending_props_pb.BalanceDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    pending: jspb.Message.getFieldWithDefault(msg, 1, ""),
    totalPending: jspb.Message.getFieldWithDefault(msg, 2, ""),
    transferable: jspb.Message.getFieldWithDefault(msg, 3, ""),
    bonded: jspb.Message.getFieldWithDefault(msg, 4, ""),
    delegated: jspb.Message.getFieldWithDefault(msg, 5, ""),
    delegatedto: jspb.Message.getFieldWithDefault(msg, 6, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 7, 0),
    lastEthBlockId: jspb.Message.getFieldWithDefault(msg, 8, 0),
    lastUpdateType: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pending_props_pb.BalanceDetails}
 */
proto.pending_props_pb.BalanceDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pending_props_pb.BalanceDetails;
  return proto.pending_props_pb.BalanceDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pending_props_pb.BalanceDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pending_props_pb.BalanceDetails}
 */
proto.pending_props_pb.BalanceDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPending(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTotalPending(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransferable(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBonded(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDelegated(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDelegatedto(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastEthBlockId(value);
      break;
    case 9:
      var value = /** @type {!proto.pending_props_pb.UpdateType} */ (reader.readEnum());
      msg.setLastUpdateType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pending_props_pb.BalanceDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pending_props_pb.BalanceDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pending_props_pb.BalanceDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pending_props_pb.BalanceDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPending();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTotalPending();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTransferable();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBonded();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDelegated();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDelegatedto();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getLastEthBlockId();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getLastUpdateType();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional string pending = 1;
 * @return {string}
 */
proto.pending_props_pb.BalanceDetails.prototype.getPending = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.pending_props_pb.BalanceDetails.prototype.setPending = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string total_pending = 2;
 * @return {string}
 */
proto.pending_props_pb.BalanceDetails.prototype.getTotalPending = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.pending_props_pb.BalanceDetails.prototype.setTotalPending = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string transferable = 3;
 * @return {string}
 */
proto.pending_props_pb.BalanceDetails.prototype.getTransferable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.pending_props_pb.BalanceDetails.prototype.setTransferable = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string bonded = 4;
 * @return {string}
 */
proto.pending_props_pb.BalanceDetails.prototype.getBonded = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.pending_props_pb.BalanceDetails.prototype.setBonded = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string delegated = 5;
 * @return {string}
 */
proto.pending_props_pb.BalanceDetails.prototype.getDelegated = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.pending_props_pb.BalanceDetails.prototype.setDelegated = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string delegatedTo = 6;
 * @return {string}
 */
proto.pending_props_pb.BalanceDetails.prototype.getDelegatedto = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.pending_props_pb.BalanceDetails.prototype.setDelegatedto = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 timestamp = 7;
 * @return {number}
 */
proto.pending_props_pb.BalanceDetails.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.pending_props_pb.BalanceDetails.prototype.setTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 last_eth_block_id = 8;
 * @return {number}
 */
proto.pending_props_pb.BalanceDetails.prototype.getLastEthBlockId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.pending_props_pb.BalanceDetails.prototype.setLastEthBlockId = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional UpdateType last_update_type = 9;
 * @return {!proto.pending_props_pb.UpdateType}
 */
proto.pending_props_pb.BalanceDetails.prototype.getLastUpdateType = function() {
  return /** @type {!proto.pending_props_pb.UpdateType} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {!proto.pending_props_pb.UpdateType} value */
proto.pending_props_pb.BalanceDetails.prototype.setLastUpdateType = function(value) {
  jspb.Message.setProto3EnumField(this, 9, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pending_props_pb.Balance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pending_props_pb.Balance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pending_props_pb.Balance.displayName = 'proto.pending_props_pb.Balance';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pending_props_pb.Balance.prototype.toObject = function(opt_includeInstance) {
  return proto.pending_props_pb.Balance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pending_props_pb.Balance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pending_props_pb.Balance.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    applicationId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    balanceDetails: (f = msg.getBalanceDetails()) && proto.pending_props_pb.BalanceDetails.toObject(includeInstance, f),
    preCutoffDetails: (f = msg.getPreCutoffDetails()) && proto.pending_props_pb.BalanceDetails.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 5, 0),
    linkedWallet: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pending_props_pb.Balance}
 */
proto.pending_props_pb.Balance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pending_props_pb.Balance;
  return proto.pending_props_pb.Balance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pending_props_pb.Balance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pending_props_pb.Balance}
 */
proto.pending_props_pb.Balance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplicationId(value);
      break;
    case 3:
      var value = new proto.pending_props_pb.BalanceDetails;
      reader.readMessage(value,proto.pending_props_pb.BalanceDetails.deserializeBinaryFromReader);
      msg.setBalanceDetails(value);
      break;
    case 4:
      var value = new proto.pending_props_pb.BalanceDetails;
      reader.readMessage(value,proto.pending_props_pb.BalanceDetails.deserializeBinaryFromReader);
      msg.setPreCutoffDetails(value);
      break;
    case 5:
      var value = /** @type {!proto.pending_props_pb.BalanceType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLinkedWallet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pending_props_pb.Balance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pending_props_pb.Balance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pending_props_pb.Balance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pending_props_pb.Balance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApplicationId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBalanceDetails();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.pending_props_pb.BalanceDetails.serializeBinaryToWriter
    );
  }
  f = message.getPreCutoffDetails();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.pending_props_pb.BalanceDetails.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getLinkedWallet();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.pending_props_pb.Balance.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.pending_props_pb.Balance.prototype.setUserId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string application_id = 2;
 * @return {string}
 */
proto.pending_props_pb.Balance.prototype.getApplicationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.pending_props_pb.Balance.prototype.setApplicationId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional BalanceDetails balance_details = 3;
 * @return {?proto.pending_props_pb.BalanceDetails}
 */
proto.pending_props_pb.Balance.prototype.getBalanceDetails = function() {
  return /** @type{?proto.pending_props_pb.BalanceDetails} */ (
    jspb.Message.getWrapperField(this, proto.pending_props_pb.BalanceDetails, 3));
};


/** @param {?proto.pending_props_pb.BalanceDetails|undefined} value */
proto.pending_props_pb.Balance.prototype.setBalanceDetails = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.pending_props_pb.Balance.prototype.clearBalanceDetails = function() {
  this.setBalanceDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.pending_props_pb.Balance.prototype.hasBalanceDetails = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional BalanceDetails pre_cutoff_details = 4;
 * @return {?proto.pending_props_pb.BalanceDetails}
 */
proto.pending_props_pb.Balance.prototype.getPreCutoffDetails = function() {
  return /** @type{?proto.pending_props_pb.BalanceDetails} */ (
    jspb.Message.getWrapperField(this, proto.pending_props_pb.BalanceDetails, 4));
};


/** @param {?proto.pending_props_pb.BalanceDetails|undefined} value */
proto.pending_props_pb.Balance.prototype.setPreCutoffDetails = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.pending_props_pb.Balance.prototype.clearPreCutoffDetails = function() {
  this.setPreCutoffDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.pending_props_pb.Balance.prototype.hasPreCutoffDetails = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional BalanceType type = 5;
 * @return {!proto.pending_props_pb.BalanceType}
 */
proto.pending_props_pb.Balance.prototype.getType = function() {
  return /** @type {!proto.pending_props_pb.BalanceType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.pending_props_pb.BalanceType} value */
proto.pending_props_pb.Balance.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string linked_wallet = 6;
 * @return {string}
 */
proto.pending_props_pb.Balance.prototype.getLinkedWallet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.pending_props_pb.Balance.prototype.setLinkedWallet = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * @enum {number}
 */
proto.pending_props_pb.BalanceType = {
  USER: 0,
  WALLET: 1
};

/**
 * @enum {number}
 */
proto.pending_props_pb.UpdateType = {
  PENDING_PROPS_BALANCE: 0,
  PROPS_BALANCE: 1
};

goog.object.extend(exports, proto.pending_props_pb);
