// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package pending_props_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActivityLog struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApplicationId        string   `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Date                 int32    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityLog) Reset()         { *m = ActivityLog{} }
func (m *ActivityLog) String() string { return proto.CompactTextString(m) }
func (*ActivityLog) ProtoMessage()    {}
func (*ActivityLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{0}
}

func (m *ActivityLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityLog.Unmarshal(m, b)
}
func (m *ActivityLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityLog.Marshal(b, m, deterministic)
}
func (m *ActivityLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityLog.Merge(m, src)
}
func (m *ActivityLog) XXX_Size() int {
	return xxx_messageInfo_ActivityLog.Size(m)
}
func (m *ActivityLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityLog.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityLog proto.InternalMessageInfo

func (m *ActivityLog) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ActivityLog) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *ActivityLog) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *ActivityLog) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*ActivityLog)(nil), "pending_props_pb.ActivityLog")
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_a684c9a0549e7832) }

var fileDescriptor_a684c9a0549e7832 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4c, 0x2e, 0xc9,
	0x2c, 0xcb, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x28, 0x48, 0xcd, 0x4b,
	0xc9, 0xcc, 0x4b, 0x8f, 0x2f, 0x28, 0xca, 0x2f, 0x28, 0x8e, 0x2f, 0x48, 0x52, 0xaa, 0xe7, 0xe2,
	0x76, 0x84, 0xaa, 0xf1, 0xc9, 0x4f, 0x17, 0x12, 0xe7, 0x62, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0xcf,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0x54, 0xb9,
	0xf8, 0x12, 0x0b, 0x0a, 0x72, 0x32, 0x93, 0x13, 0x4b, 0x32, 0xf3, 0xf3, 0x40, 0xf2, 0x4c, 0x60,
	0x79, 0x5e, 0x24, 0x51, 0xcf, 0x14, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x54, 0x09, 0x66,
	0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0x48, 0x86, 0x8b, 0xb3, 0x24, 0x33, 0x37, 0xb5, 0xb8,
	0x24, 0x31, 0xb7, 0x40, 0x82, 0x45, 0x81, 0x51, 0x83, 0x39, 0x08, 0x21, 0x90, 0xc4, 0x06, 0x76,
	0x99, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x7c, 0x88, 0xfb, 0xab, 0x00, 0x00, 0x00,
}
