// Code generated by protoc-gen-go. DO NOT EDIT.
// source: earning.proto

package pending_props_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_PENDING Status = 0
	Status_REVOKED Status = 1
	Status_SETTLED Status = 2
	Status_ERROR   Status = 3
)

var Status_name = map[int32]string{
	0: "PENDING",
	1: "REVOKED",
	2: "SETTLED",
	3: "ERROR",
}

var Status_value = map[string]int32{
	"PENDING": 0,
	"REVOKED": 1,
	"SETTLED": 2,
	"ERROR":   3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b2120c7d29ace5bf, []int{0}
}

type Earning struct {
	Details              *EarningDetails `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	Signature            string          `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SettledByTransaction string          `protobuf:"bytes,3,opt,name=settled_by_transaction,json=settledByTransaction,proto3" json:"settled_by_transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Earning) Reset()         { *m = Earning{} }
func (m *Earning) String() string { return proto.CompactTextString(m) }
func (*Earning) ProtoMessage()    {}
func (*Earning) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2120c7d29ace5bf, []int{0}
}

func (m *Earning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Earning.Unmarshal(m, b)
}
func (m *Earning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Earning.Marshal(b, m, deterministic)
}
func (m *Earning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Earning.Merge(m, src)
}
func (m *Earning) XXX_Size() int {
	return xxx_messageInfo_Earning.Size(m)
}
func (m *Earning) XXX_DiscardUnknown() {
	xxx_messageInfo_Earning.DiscardUnknown(m)
}

var xxx_messageInfo_Earning proto.InternalMessageInfo

func (m *Earning) GetDetails() *EarningDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Earning) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Earning) GetSettledByTransaction() string {
	if m != nil {
		return m.SettledByTransaction
	}
	return ""
}

type EarningDetails struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AmountEarned         string   `protobuf:"bytes,2,opt,name=amount_earned,json=amountEarned,proto3" json:"amount_earned,omitempty"`
	AmountSettled        string   `protobuf:"bytes,3,opt,name=amount_settled,json=amountSettled,proto3" json:"amount_settled,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApplicationId        string   `protobuf:"bytes,5,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status               Status   `protobuf:"varint,7,opt,name=status,proto3,enum=pending_props_pb.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EarningDetails) Reset()         { *m = EarningDetails{} }
func (m *EarningDetails) String() string { return proto.CompactTextString(m) }
func (*EarningDetails) ProtoMessage()    {}
func (*EarningDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2120c7d29ace5bf, []int{1}
}

func (m *EarningDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EarningDetails.Unmarshal(m, b)
}
func (m *EarningDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EarningDetails.Marshal(b, m, deterministic)
}
func (m *EarningDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EarningDetails.Merge(m, src)
}
func (m *EarningDetails) XXX_Size() int {
	return xxx_messageInfo_EarningDetails.Size(m)
}
func (m *EarningDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_EarningDetails.DiscardUnknown(m)
}

var xxx_messageInfo_EarningDetails proto.InternalMessageInfo

func (m *EarningDetails) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EarningDetails) GetAmountEarned() string {
	if m != nil {
		return m.AmountEarned
	}
	return ""
}

func (m *EarningDetails) GetAmountSettled() string {
	if m != nil {
		return m.AmountSettled
	}
	return ""
}

func (m *EarningDetails) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *EarningDetails) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *EarningDetails) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EarningDetails) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_PENDING
}

type Settlements struct {
	EarningAddresses     []string `protobuf:"bytes,1,rep,name=earning_addresses,json=earningAddresses,proto3" json:"earning_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Settlements) Reset()         { *m = Settlements{} }
func (m *Settlements) String() string { return proto.CompactTextString(m) }
func (*Settlements) ProtoMessage()    {}
func (*Settlements) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2120c7d29ace5bf, []int{2}
}

func (m *Settlements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settlements.Unmarshal(m, b)
}
func (m *Settlements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settlements.Marshal(b, m, deterministic)
}
func (m *Settlements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settlements.Merge(m, src)
}
func (m *Settlements) XXX_Size() int {
	return xxx_messageInfo_Settlements.Size(m)
}
func (m *Settlements) XXX_DiscardUnknown() {
	xxx_messageInfo_Settlements.DiscardUnknown(m)
}

var xxx_messageInfo_Settlements proto.InternalMessageInfo

func (m *Settlements) GetEarningAddresses() []string {
	if m != nil {
		return m.EarningAddresses
	}
	return nil
}

type LastEthBlock struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastEthBlock) Reset()         { *m = LastEthBlock{} }
func (m *LastEthBlock) String() string { return proto.CompactTextString(m) }
func (*LastEthBlock) ProtoMessage()    {}
func (*LastEthBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2120c7d29ace5bf, []int{3}
}

func (m *LastEthBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastEthBlock.Unmarshal(m, b)
}
func (m *LastEthBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastEthBlock.Marshal(b, m, deterministic)
}
func (m *LastEthBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastEthBlock.Merge(m, src)
}
func (m *LastEthBlock) XXX_Size() int {
	return xxx_messageInfo_LastEthBlock.Size(m)
}
func (m *LastEthBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_LastEthBlock.DiscardUnknown(m)
}

var xxx_messageInfo_LastEthBlock proto.InternalMessageInfo

func (m *LastEthBlock) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LastEthBlock) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Nonce struct {
	Current              int64    `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nonce) Reset()         { *m = Nonce{} }
func (m *Nonce) String() string { return proto.CompactTextString(m) }
func (*Nonce) ProtoMessage()    {}
func (*Nonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2120c7d29ace5bf, []int{4}
}

func (m *Nonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nonce.Unmarshal(m, b)
}
func (m *Nonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nonce.Marshal(b, m, deterministic)
}
func (m *Nonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nonce.Merge(m, src)
}
func (m *Nonce) XXX_Size() int {
	return xxx_messageInfo_Nonce.Size(m)
}
func (m *Nonce) XXX_DiscardUnknown() {
	xxx_messageInfo_Nonce.DiscardUnknown(m)
}

var xxx_messageInfo_Nonce proto.InternalMessageInfo

func (m *Nonce) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterEnum("pending_props_pb.Status", Status_name, Status_value)
	proto.RegisterType((*Earning)(nil), "pending_props_pb.Earning")
	proto.RegisterType((*EarningDetails)(nil), "pending_props_pb.EarningDetails")
	proto.RegisterType((*Settlements)(nil), "pending_props_pb.Settlements")
	proto.RegisterType((*LastEthBlock)(nil), "pending_props_pb.LastEthBlock")
	proto.RegisterType((*Nonce)(nil), "pending_props_pb.Nonce")
}

func init() { proto.RegisterFile("earning.proto", fileDescriptor_b2120c7d29ace5bf) }

var fileDescriptor_b2120c7d29ace5bf = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0x36, 0xa9, 0x4d, 0xe8, 0xeb, 0x6e, 0x89, 0x83, 0x68, 0x0e, 0x1e, 0x62, 0x44, 0x28, 0x0a,
	0x45, 0x56, 0x4f, 0xc5, 0x8b, 0x4b, 0x07, 0x29, 0x2e, 0x5d, 0x99, 0x16, 0xaf, 0x61, 0x9a, 0x19,
	0xea, 0x60, 0x3b, 0x19, 0x66, 0x5e, 0x0e, 0xfb, 0x4f, 0x78, 0xf7, 0xbf, 0x95, 0x4c, 0xa6, 0xc4,
	0xad, 0xc7, 0xf7, 0xfd, 0xe0, 0x7d, 0xf3, 0xbd, 0x81, 0x6b, 0xc9, 0xad, 0x56, 0xfa, 0xb0, 0x30,
	0xb6, 0xc1, 0x86, 0x64, 0x46, 0x6a, 0xa1, 0xf4, 0xa1, 0x32, 0xb6, 0x31, 0xae, 0x32, 0xfb, 0xf2,
	0x4f, 0x04, 0x29, 0xed, 0x35, 0x64, 0x09, 0xa9, 0x90, 0xc8, 0xd5, 0xd1, 0xe5, 0x51, 0x11, 0xcd,
	0xa7, 0x37, 0xc5, 0xe2, 0x52, 0xbf, 0x08, 0xda, 0x55, 0xaf, 0x63, 0x67, 0x03, 0x79, 0x05, 0x13,
	0xa7, 0x0e, 0x9a, 0x63, 0x6b, 0x65, 0x1e, 0x17, 0xd1, 0x7c, 0xc2, 0x06, 0x80, 0x7c, 0x82, 0x17,
	0x4e, 0x22, 0x1e, 0xa5, 0xa8, 0xf6, 0x0f, 0x15, 0x5a, 0xae, 0x1d, 0xaf, 0x51, 0x35, 0x3a, 0x1f,
	0x79, 0xe9, 0xf3, 0xc0, 0xde, 0x3e, 0xec, 0x06, 0xae, 0xfc, 0x1d, 0xc3, 0xec, 0xf1, 0xbe, 0x6e,
	0x0d, 0xaa, 0x93, 0x74, 0xc8, 0x4f, 0xc6, 0x87, 0x1c, 0xb1, 0x01, 0x20, 0x6f, 0xe0, 0x9a, 0x9f,
	0x9a, 0x56, 0x63, 0xd5, 0x3d, 0x5b, 0x8a, 0x10, 0xe4, 0xaa, 0x07, 0xa9, 0xc7, 0xc8, 0x5b, 0x98,
	0x05, 0x51, 0x58, 0x1a, 0x32, 0x04, 0xeb, 0xb6, 0x07, 0xc9, 0x4b, 0x48, 0x5b, 0x27, 0x6d, 0xa5,
	0x44, 0xfe, 0xd4, 0xf3, 0x49, 0x37, 0xae, 0x7b, 0xbf, 0x31, 0x47, 0x55, 0xf3, 0x2e, 0x64, 0xc7,
	0x8f, 0x83, 0x7f, 0x40, 0xd7, 0x82, 0x14, 0x30, 0x15, 0xd2, 0xd5, 0x56, 0x19, 0xff, 0xce, 0xc4,
	0x6b, 0xfe, 0x85, 0xc8, 0x07, 0x48, 0x1c, 0x72, 0x6c, 0x5d, 0x9e, 0x16, 0xd1, 0x7c, 0x76, 0x93,
	0xff, 0xdf, 0xf6, 0xd6, 0xf3, 0x2c, 0xe8, 0xca, 0x25, 0x4c, 0xfb, 0x78, 0x27, 0xa9, 0xd1, 0x91,
	0xf7, 0xf0, 0x2c, 0x9c, 0xb7, 0xe2, 0x42, 0x58, 0xe9, 0x9c, 0xec, 0x2e, 0x37, 0x9a, 0x4f, 0x58,
	0x16, 0x88, 0x2f, 0x67, 0xbc, 0xfc, 0x0c, 0x57, 0x77, 0xdc, 0x21, 0xc5, 0x9f, 0xb7, 0xc7, 0xa6,
	0xfe, 0x45, 0x66, 0x10, 0x2b, 0x11, 0x2a, 0x8c, 0x95, 0x78, 0xdc, 0x6c, 0x7c, 0xd1, 0x6c, 0xf9,
	0x1a, 0xc6, 0x9b, 0x46, 0xd7, 0x92, 0xe4, 0x90, 0xd6, 0xad, 0xb5, 0x52, 0x63, 0xf0, 0x9e, 0xc7,
	0x77, 0x4b, 0x48, 0xfa, 0xb8, 0x64, 0x0a, 0xe9, 0x77, 0xba, 0x59, 0xad, 0x37, 0x5f, 0xb3, 0x27,
	0xdd, 0xc0, 0xe8, 0x8f, 0xfb, 0x6f, 0x74, 0x95, 0x45, 0xdd, 0xb0, 0xa5, 0xbb, 0xdd, 0x1d, 0x5d,
	0x65, 0x31, 0x99, 0xc0, 0x98, 0x32, 0x76, 0xcf, 0xb2, 0xd1, 0x3e, 0xf1, 0xdf, 0xf3, 0xe3, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x4f, 0x1f, 0xe1, 0xaf, 0x02, 0x00, 0x00,
}
