// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package pending_props_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_EarningIssued       EventType = 0
	EventType_EarningRevoked      EventType = 1
	EventType_EarningSettled      EventType = 2
	EventType_BalanceUpdated      EventType = 3
	EventType_LastEthBlockUpdated EventType = 4
	EventType_WalletLinked        EventType = 5
	EventType_WalletUnlinked      EventType = 6
	EventType_TransactionAdded    EventType = 7
	EventType_RewardEntityUpdated EventType = 8
)

var EventType_name = map[int32]string{
	0: "EarningIssued",
	1: "EarningRevoked",
	2: "EarningSettled",
	3: "BalanceUpdated",
	4: "LastEthBlockUpdated",
	5: "WalletLinked",
	6: "WalletUnlinked",
	7: "TransactionAdded",
	8: "RewardEntityUpdated",
}

var EventType_value = map[string]int32{
	"EarningIssued":       0,
	"EarningRevoked":      1,
	"EarningSettled":      2,
	"BalanceUpdated":      3,
	"LastEthBlockUpdated": 4,
	"WalletLinked":        5,
	"WalletUnlinked":      6,
	"TransactionAdded":    7,
	"RewardEntityUpdated": 8,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

type TransactionEvent struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Type                 Method       `protobuf:"varint,2,opt,name=type,proto3,enum=pending_props_pb.Method" json:"type,omitempty"`
	StateAddress         string       `protobuf:"bytes,3,opt,name=stateAddress,proto3" json:"stateAddress,omitempty"`
	Message              string       `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Description          string       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransactionEvent) Reset()         { *m = TransactionEvent{} }
func (m *TransactionEvent) String() string { return proto.CompactTextString(m) }
func (*TransactionEvent) ProtoMessage()    {}
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *TransactionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEvent.Unmarshal(m, b)
}
func (m *TransactionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEvent.Marshal(b, m, deterministic)
}
func (m *TransactionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEvent.Merge(m, src)
}
func (m *TransactionEvent) XXX_Size() int {
	return xxx_messageInfo_TransactionEvent.Size(m)
}
func (m *TransactionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEvent proto.InternalMessageInfo

func (m *TransactionEvent) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *TransactionEvent) GetType() Method {
	if m != nil {
		return m.Type
	}
	return Method_ISSUE
}

func (m *TransactionEvent) GetStateAddress() string {
	if m != nil {
		return m.StateAddress
	}
	return ""
}

func (m *TransactionEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TransactionEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type BalanceEvent struct {
	Balance              *Balance `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceEvent) Reset()         { *m = BalanceEvent{} }
func (m *BalanceEvent) String() string { return proto.CompactTextString(m) }
func (*BalanceEvent) ProtoMessage()    {}
func (*BalanceEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *BalanceEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceEvent.Unmarshal(m, b)
}
func (m *BalanceEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceEvent.Marshal(b, m, deterministic)
}
func (m *BalanceEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceEvent.Merge(m, src)
}
func (m *BalanceEvent) XXX_Size() int {
	return xxx_messageInfo_BalanceEvent.Size(m)
}
func (m *BalanceEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceEvent.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceEvent proto.InternalMessageInfo

func (m *BalanceEvent) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *BalanceEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BalanceEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type LastEthBlockEvent struct {
	BlockId              int64    `protobuf:"varint,1,opt,name=blockId,proto3" json:"blockId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastEthBlockEvent) Reset()         { *m = LastEthBlockEvent{} }
func (m *LastEthBlockEvent) String() string { return proto.CompactTextString(m) }
func (*LastEthBlockEvent) ProtoMessage()    {}
func (*LastEthBlockEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *LastEthBlockEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastEthBlockEvent.Unmarshal(m, b)
}
func (m *LastEthBlockEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastEthBlockEvent.Marshal(b, m, deterministic)
}
func (m *LastEthBlockEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastEthBlockEvent.Merge(m, src)
}
func (m *LastEthBlockEvent) XXX_Size() int {
	return xxx_messageInfo_LastEthBlockEvent.Size(m)
}
func (m *LastEthBlockEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LastEthBlockEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LastEthBlockEvent proto.InternalMessageInfo

func (m *LastEthBlockEvent) GetBlockId() int64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

func (m *LastEthBlockEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LastEthBlockEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type WalletLinkedEvent struct {
	User                 *ApplicationUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	WalletToUsers        *WalletToUser    `protobuf:"bytes,2,opt,name=walletToUsers,proto3" json:"walletToUsers,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WalletLinkedEvent) Reset()         { *m = WalletLinkedEvent{} }
func (m *WalletLinkedEvent) String() string { return proto.CompactTextString(m) }
func (*WalletLinkedEvent) ProtoMessage()    {}
func (*WalletLinkedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{3}
}

func (m *WalletLinkedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletLinkedEvent.Unmarshal(m, b)
}
func (m *WalletLinkedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletLinkedEvent.Marshal(b, m, deterministic)
}
func (m *WalletLinkedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletLinkedEvent.Merge(m, src)
}
func (m *WalletLinkedEvent) XXX_Size() int {
	return xxx_messageInfo_WalletLinkedEvent.Size(m)
}
func (m *WalletLinkedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletLinkedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_WalletLinkedEvent proto.InternalMessageInfo

func (m *WalletLinkedEvent) GetUser() *ApplicationUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *WalletLinkedEvent) GetWalletToUsers() *WalletToUser {
	if m != nil {
		return m.WalletToUsers
	}
	return nil
}

func (m *WalletLinkedEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type WalletUnlinkedEvent struct {
	User                 *ApplicationUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	WalletToUsers        *WalletToUser    `protobuf:"bytes,2,opt,name=walletToUsers,proto3" json:"walletToUsers,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WalletUnlinkedEvent) Reset()         { *m = WalletUnlinkedEvent{} }
func (m *WalletUnlinkedEvent) String() string { return proto.CompactTextString(m) }
func (*WalletUnlinkedEvent) ProtoMessage()    {}
func (*WalletUnlinkedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{4}
}

func (m *WalletUnlinkedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletUnlinkedEvent.Unmarshal(m, b)
}
func (m *WalletUnlinkedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletUnlinkedEvent.Marshal(b, m, deterministic)
}
func (m *WalletUnlinkedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletUnlinkedEvent.Merge(m, src)
}
func (m *WalletUnlinkedEvent) XXX_Size() int {
	return xxx_messageInfo_WalletUnlinkedEvent.Size(m)
}
func (m *WalletUnlinkedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletUnlinkedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_WalletUnlinkedEvent proto.InternalMessageInfo

func (m *WalletUnlinkedEvent) GetUser() *ApplicationUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *WalletUnlinkedEvent) GetWalletToUsers() *WalletToUser {
	if m != nil {
		return m.WalletToUsers
	}
	return nil
}

func (m *WalletUnlinkedEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RewardEntityUpdateEvent struct {
	Entity               *RewardEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RewardEntityUpdateEvent) Reset()         { *m = RewardEntityUpdateEvent{} }
func (m *RewardEntityUpdateEvent) String() string { return proto.CompactTextString(m) }
func (*RewardEntityUpdateEvent) ProtoMessage()    {}
func (*RewardEntityUpdateEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{5}
}

func (m *RewardEntityUpdateEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardEntityUpdateEvent.Unmarshal(m, b)
}
func (m *RewardEntityUpdateEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardEntityUpdateEvent.Marshal(b, m, deterministic)
}
func (m *RewardEntityUpdateEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardEntityUpdateEvent.Merge(m, src)
}
func (m *RewardEntityUpdateEvent) XXX_Size() int {
	return xxx_messageInfo_RewardEntityUpdateEvent.Size(m)
}
func (m *RewardEntityUpdateEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardEntityUpdateEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RewardEntityUpdateEvent proto.InternalMessageInfo

func (m *RewardEntityUpdateEvent) GetEntity() *RewardEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *RewardEntityUpdateEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("pending_props_pb.EventType", EventType_name, EventType_value)
	proto.RegisterType((*TransactionEvent)(nil), "pending_props_pb.TransactionEvent")
	proto.RegisterType((*BalanceEvent)(nil), "pending_props_pb.BalanceEvent")
	proto.RegisterType((*LastEthBlockEvent)(nil), "pending_props_pb.LastEthBlockEvent")
	proto.RegisterType((*WalletLinkedEvent)(nil), "pending_props_pb.WalletLinkedEvent")
	proto.RegisterType((*WalletUnlinkedEvent)(nil), "pending_props_pb.WalletUnlinkedEvent")
	proto.RegisterType((*RewardEntityUpdateEvent)(nil), "pending_props_pb.RewardEntityUpdateEvent")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xc1, 0x6e, 0x1a, 0x3d,
	0x10, 0xfe, 0x97, 0x25, 0xf0, 0x33, 0x40, 0x64, 0x9c, 0x56, 0xd9, 0xa2, 0xb6, 0xa2, 0x9c, 0x50,
	0x55, 0x71, 0x20, 0x6a, 0xaf, 0x15, 0x51, 0x39, 0x44, 0x4a, 0x2f, 0x2e, 0x28, 0x47, 0x64, 0xf0,
	0x88, 0xac, 0x58, 0xbc, 0xd6, 0xda, 0x49, 0xc4, 0xa9, 0xef, 0x53, 0xf5, 0x41, 0xfa, 0x1a, 0x7d,
	0x93, 0xca, 0x5e, 0xa3, 0x98, 0x6e, 0x9b, 0x73, 0x8f, 0xf3, 0xf9, 0xfb, 0x66, 0xbe, 0xb1, 0x67,
	0x0c, 0x1d, 0xbc, 0x47, 0x69, 0xf4, 0x58, 0x15, 0xb9, 0xc9, 0x29, 0x51, 0x28, 0x45, 0x2a, 0x37,
	0x4b, 0x55, 0xe4, 0x4a, 0x2f, 0xd5, 0xaa, 0xdf, 0x55, 0x7c, 0x9f, 0xe5, 0x5c, 0x94, 0x84, 0x7e,
	0x77, 0xc5, 0x33, 0x2e, 0xd7, 0xe8, 0xc3, 0xf6, 0x9d, 0xc6, 0xc2, 0x8b, 0xfb, 0x3d, 0x53, 0x70,
	0xa9, 0xf9, 0xda, 0xa4, 0xb9, 0xf4, 0xd0, 0xf3, 0x02, 0x1f, 0x78, 0x21, 0x96, 0x28, 0x4d, 0x6a,
	0x52, 0xf4, 0xcc, 0xe1, 0xcf, 0x08, 0xc8, 0xfc, 0x91, 0x3c, 0xb3, 0x16, 0xe8, 0x47, 0x68, 0x07,
	0x09, 0x92, 0x68, 0x10, 0x8d, 0xda, 0x93, 0x57, 0xe3, 0xdf, 0x1d, 0x8d, 0x03, 0x21, 0x0b, 0x15,
	0xf4, 0x1d, 0xd4, 0xcd, 0x5e, 0x61, 0x52, 0x1b, 0x44, 0xa3, 0xd3, 0x49, 0x52, 0x55, 0x7e, 0x46,
	0x73, 0x9b, 0x0b, 0xe6, 0x58, 0x74, 0x08, 0x1d, 0x6d, 0xb8, 0xc1, 0xa9, 0x10, 0x05, 0x6a, 0x9d,
	0xc4, 0x83, 0x68, 0xd4, 0x62, 0x47, 0x18, 0x4d, 0xa0, 0xb9, 0x43, 0xad, 0xf9, 0x06, 0x93, 0xba,
	0x3b, 0x3e, 0x84, 0x74, 0x00, 0x6d, 0x81, 0x7a, 0x5d, 0xa4, 0xca, 0x99, 0x3d, 0x71, 0xa7, 0x21,
	0x34, 0xfc, 0x0a, 0x9d, 0xcb, 0xf2, 0xae, 0xca, 0xf6, 0x2e, 0xa0, 0xe9, 0xef, 0xce, 0xb7, 0xf6,
	0xa2, 0x6a, 0xd0, 0x0b, 0xd8, 0x81, 0x19, 0x1a, 0xa8, 0x3d, 0x69, 0x20, 0xae, 0x1a, 0x40, 0xe8,
	0x5d, 0x73, 0x6d, 0x66, 0xe6, 0xf6, 0x32, 0xcb, 0xd7, 0xdb, 0xd2, 0x45, 0x02, 0xcd, 0x95, 0x8d,
	0xae, 0x84, 0x73, 0x11, 0xb3, 0x43, 0xf8, 0x44, 0xa9, 0x97, 0xd0, 0x32, 0xe9, 0x0e, 0xb5, 0xe1,
	0x3b, 0xe5, 0x0a, 0xc5, 0xec, 0x11, 0x18, 0x7e, 0x8b, 0xa0, 0x77, 0xc3, 0xb3, 0x0c, 0xcd, 0x75,
	0x2a, 0xb7, 0x28, 0xca, 0x3a, 0xef, 0xa1, 0x6e, 0x47, 0xc3, 0xb7, 0xfa, 0xa6, 0xda, 0xea, 0x54,
	0xa9, 0x2c, 0x5d, 0x73, 0xeb, 0x74, 0xa1, 0xb1, 0x60, 0x8e, 0x4e, 0x3f, 0x41, 0xf7, 0xc1, 0xe5,
	0x9a, 0xe7, 0x16, 0xd5, 0xce, 0x4a, 0x7b, 0xf2, 0xba, 0xaa, 0xbf, 0x09, 0x68, 0xec, 0x58, 0x14,
	0xb6, 0x12, 0x1f, 0xb5, 0x32, 0xfc, 0x1e, 0xc1, 0x59, 0xa9, 0x5c, 0xc8, 0xec, 0xdf, 0xb7, 0xbb,
	0x85, 0x73, 0xe6, 0x16, 0x68, 0x66, 0xf7, 0x67, 0xbf, 0x50, 0x82, 0x1b, 0x3f, 0x4e, 0x1f, 0xa0,
	0xe1, 0x96, 0x6a, 0xef, 0x3d, 0xff, 0xa1, 0x66, 0x28, 0x65, 0x9e, 0xfd, 0xf7, 0x67, 0x7e, 0xfb,
	0x23, 0x82, 0x96, 0xcb, 0x3d, 0xb7, 0xeb, 0xd1, 0x83, 0xee, 0x8c, 0x17, 0x32, 0x95, 0x9b, 0x2b,
	0xad, 0xef, 0x50, 0x90, 0xff, 0x28, 0x85, 0x53, 0x0f, 0x31, 0xbc, 0xcf, 0xb7, 0x28, 0x48, 0x14,
	0x60, 0x5f, 0xd0, 0x98, 0x0c, 0x05, 0xa9, 0x59, 0xcc, 0x0f, 0x72, 0x69, 0x58, 0x90, 0x98, 0x9e,
	0xc3, 0x59, 0x38, 0x8c, 0x87, 0x83, 0x3a, 0x25, 0xd0, 0x09, 0xa7, 0x87, 0x9c, 0x58, 0xf9, 0xf1,
	0x13, 0x91, 0x06, 0x7d, 0x76, 0xf4, 0x5f, 0x4c, 0x85, 0x40, 0x41, 0x9a, 0x36, 0x69, 0xf5, 0x7a,
	0x04, 0xf9, 0x7f, 0xd5, 0x70, 0xdf, 0xcc, 0xc5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x3c,
	0xed, 0x8f, 0xdd, 0x04, 0x00, 0x00,
}
