// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

package pending_props_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Method int32

const (
	Method_ISSUE                 Method = 0
	Method_REVOKE                Method = 1
	Method_SETTLE                Method = 2
	Method_BALANCE_UPDATE        Method = 3
	Method_LAST_ETH_BLOCK_UPDATE Method = 4
	Method_WALLET_LINK           Method = 5
	Method_ACTIVITY_LOG          Method = 6
	Method_REWARD_ENTITY_UPDATE  Method = 7
)

var Method_name = map[int32]string{
	0: "ISSUE",
	1: "REVOKE",
	2: "SETTLE",
	3: "BALANCE_UPDATE",
	4: "LAST_ETH_BLOCK_UPDATE",
	5: "WALLET_LINK",
	6: "ACTIVITY_LOG",
	7: "REWARD_ENTITY_UPDATE",
}

var Method_value = map[string]int32{
	"ISSUE":                 0,
	"REVOKE":                1,
	"SETTLE":                2,
	"BALANCE_UPDATE":        3,
	"LAST_ETH_BLOCK_UPDATE": 4,
	"WALLET_LINK":           5,
	"ACTIVITY_LOG":          6,
	"REWARD_ENTITY_UPDATE":  7,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}

func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0}
}

type Params struct {
	Data                 *any.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

//@Todo add nonce
type RPCRequest struct {
	Method               Method   `protobuf:"varint,1,opt,name=method,proto3,enum=pending_props_pb.Method" json:"method,omitempty"`
	Params               *Params  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCRequest) Reset()         { *m = RPCRequest{} }
func (m *RPCRequest) String() string { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()    {}
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{1}
}

func (m *RPCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRequest.Unmarshal(m, b)
}
func (m *RPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRequest.Marshal(b, m, deterministic)
}
func (m *RPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequest.Merge(m, src)
}
func (m *RPCRequest) XXX_Size() int {
	return xxx_messageInfo_RPCRequest.Size(m)
}
func (m *RPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequest proto.InternalMessageInfo

func (m *RPCRequest) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_ISSUE
}

func (m *RPCRequest) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

// Data to be submitted to TP
type BalanceUpdate struct {
	PublicAddress        string   `protobuf:"bytes,1,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	OnchainBalance       string   `protobuf:"bytes,2,opt,name=onchain_balance,json=onchainBalance,proto3" json:"onchain_balance,omitempty"`
	TxHash               string   `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockId              int64    `protobuf:"varint,6,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceUpdate) Reset()         { *m = BalanceUpdate{} }
func (m *BalanceUpdate) String() string { return proto.CompactTextString(m) }
func (*BalanceUpdate) ProtoMessage()    {}
func (*BalanceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{2}
}

func (m *BalanceUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceUpdate.Unmarshal(m, b)
}
func (m *BalanceUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceUpdate.Marshal(b, m, deterministic)
}
func (m *BalanceUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceUpdate.Merge(m, src)
}
func (m *BalanceUpdate) XXX_Size() int {
	return xxx_messageInfo_BalanceUpdate.Size(m)
}
func (m *BalanceUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceUpdate proto.InternalMessageInfo

func (m *BalanceUpdate) GetPublicAddress() string {
	if m != nil {
		return m.PublicAddress
	}
	return ""
}

func (m *BalanceUpdate) GetOnchainBalance() string {
	if m != nil {
		return m.OnchainBalance
	}
	return ""
}

func (m *BalanceUpdate) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *BalanceUpdate) GetBlockId() int64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

func (m *BalanceUpdate) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type LastEthBlock struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastEthBlock) Reset()         { *m = LastEthBlock{} }
func (m *LastEthBlock) String() string { return proto.CompactTextString(m) }
func (*LastEthBlock) ProtoMessage()    {}
func (*LastEthBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{3}
}

func (m *LastEthBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastEthBlock.Unmarshal(m, b)
}
func (m *LastEthBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastEthBlock.Marshal(b, m, deterministic)
}
func (m *LastEthBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastEthBlock.Merge(m, src)
}
func (m *LastEthBlock) XXX_Size() int {
	return xxx_messageInfo_LastEthBlock.Size(m)
}
func (m *LastEthBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_LastEthBlock.DiscardUnknown(m)
}

var xxx_messageInfo_LastEthBlock proto.InternalMessageInfo

func (m *LastEthBlock) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LastEthBlock) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("pending_props_pb.Method", Method_name, Method_value)
	proto.RegisterType((*Params)(nil), "pending_props_pb.Params")
	proto.RegisterType((*RPCRequest)(nil), "pending_props_pb.RPCRequest")
	proto.RegisterType((*BalanceUpdate)(nil), "pending_props_pb.BalanceUpdate")
	proto.RegisterType((*LastEthBlock)(nil), "pending_props_pb.LastEthBlock")
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor_678c914f1bee6d56) }

var fileDescriptor_678c914f1bee6d56 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xd1, 0x6e, 0xda, 0x30,
	0x18, 0x85, 0x97, 0x50, 0xc2, 0xf8, 0x5b, 0xd2, 0xc8, 0xea, 0xb4, 0x30, 0xed, 0xa2, 0x42, 0x9a,
	0x86, 0x76, 0x91, 0x4e, 0xec, 0x76, 0x37, 0x81, 0x5a, 0x6b, 0x44, 0x06, 0xc8, 0x84, 0x56, 0xbb,
	0xb2, 0x1c, 0xe2, 0x91, 0x68, 0x21, 0xf6, 0xb0, 0x91, 0xca, 0x93, 0xec, 0x39, 0xf6, 0x86, 0x13,
	0x4e, 0xd0, 0x24, 0xd4, 0x3b, 0xfb, 0x9c, 0xf3, 0xf9, 0x58, 0xbf, 0x7e, 0xe8, 0x49, 0x76, 0x28,
	0x05, 0xcb, 0x02, 0xb9, 0x13, 0x5a, 0x20, 0x4f, 0xf2, 0x2a, 0x2b, 0xaa, 0x0d, 0x95, 0x3b, 0x21,
	0x15, 0x95, 0xe9, 0xbb, 0xfe, 0x46, 0x88, 0x4d, 0xc9, 0xef, 0x8c, 0x9f, 0xee, 0x7f, 0xde, 0xb1,
	0xea, 0x50, 0x87, 0x07, 0x23, 0x70, 0x16, 0x6c, 0xc7, 0xb6, 0x0a, 0x0d, 0xe1, 0x22, 0x63, 0x9a,
	0xf9, 0xd6, 0xad, 0x35, 0xbc, 0x1c, 0xdd, 0x04, 0x35, 0x13, 0x9c, 0x98, 0x20, 0xac, 0x0e, 0xc4,
	0x24, 0x06, 0x12, 0x80, 0x2c, 0x26, 0x84, 0xff, 0xde, 0x73, 0xa5, 0xd1, 0x67, 0x70, 0xb6, 0x5c,
	0xe7, 0x22, 0x33, 0xa4, 0x3b, 0xf2, 0x83, 0xf3, 0xfe, 0xe0, 0xbb, 0xf1, 0x49, 0x93, 0x3b, 0x12,
	0xd2, 0x74, 0xfa, 0xb6, 0xe9, 0x7a, 0x81, 0xa8, 0xff, 0x44, 0x9a, 0xdc, 0xe0, 0xaf, 0x05, 0xbd,
	0x31, 0x2b, 0x59, 0xb5, 0xe6, 0x2b, 0x99, 0x31, 0xcd, 0xd1, 0x07, 0x70, 0xe5, 0x3e, 0x2d, 0x8b,
	0x35, 0x65, 0x59, 0xb6, 0xe3, 0x4a, 0x99, 0xf6, 0x2e, 0xe9, 0xd5, 0x6a, 0x58, 0x8b, 0xe8, 0x23,
	0x5c, 0x8b, 0x6a, 0x9d, 0xb3, 0xa2, 0xa2, 0x69, 0xcd, 0x9b, 0xce, 0x2e, 0x71, 0x1b, 0xb9, 0x79,
	0x15, 0xbd, 0x85, 0x8e, 0x7e, 0xa6, 0x39, 0x53, 0xb9, 0xdf, 0x36, 0x01, 0x47, 0x3f, 0x3f, 0x30,
	0x95, 0xa3, 0x3e, 0xbc, 0x4e, 0x4b, 0xb1, 0xfe, 0x45, 0x8b, 0xcc, 0x77, 0x6e, 0xad, 0x61, 0x8b,
	0x74, 0xcc, 0x3d, 0xca, 0xd0, 0x7b, 0xe8, 0xea, 0x62, 0xcb, 0x95, 0x66, 0x5b, 0xe9, 0x77, 0x8c,
	0xf7, 0x5f, 0x18, 0x7c, 0x85, 0xab, 0x98, 0x29, 0x8d, 0x75, 0x3e, 0x3e, 0xe6, 0x91, 0x0b, 0x76,
	0x51, 0xcf, 0xa8, 0x45, 0xec, 0xe2, 0x8c, 0xb6, 0xcf, 0xe8, 0x4f, 0x7f, 0x2c, 0x70, 0xea, 0xb1,
	0xa1, 0x2e, 0xb4, 0xa3, 0xe5, 0x72, 0x85, 0xbd, 0x57, 0x08, 0xc0, 0x21, 0xf8, 0x71, 0x3e, 0xc5,
	0x9e, 0x75, 0x3c, 0x2f, 0x71, 0x92, 0xc4, 0xd8, 0xb3, 0x11, 0x02, 0x77, 0x1c, 0xc6, 0xe1, 0x6c,
	0x82, 0xe9, 0x6a, 0x71, 0x1f, 0x26, 0xd8, 0x6b, 0xa1, 0x3e, 0xbc, 0x89, 0xc3, 0x65, 0x42, 0x71,
	0xf2, 0x40, 0xc7, 0xf1, 0x7c, 0x32, 0x3d, 0x59, 0x17, 0xe8, 0x1a, 0x2e, 0x9f, 0xc2, 0x38, 0xc6,
	0x09, 0x8d, 0xa3, 0xd9, 0xd4, 0x6b, 0x23, 0x0f, 0xae, 0xc2, 0x49, 0x12, 0x3d, 0x46, 0xc9, 0x0f,
	0x1a, 0xcf, 0xbf, 0x79, 0x0e, 0xf2, 0xe1, 0x86, 0xe0, 0xa7, 0x90, 0xdc, 0x53, 0x3c, 0x4b, 0x8e,
	0x72, 0x03, 0x77, 0x52, 0xc7, 0x6c, 0xc4, 0x97, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xd2,
	0xbf, 0x20, 0x76, 0x02, 0x00, 0x00,
}
