kind: Service
apiVersion: v1
metadata:
  name: propschain-genesis-node
spec:
  type: NodePort
  selector:
    app: propschain-genesis-node
  ports:
    - name: "4004"
      protocol: TCP
      port: 4004
      targetPort: 4004
    - name: "5050"
      protocol: TCP
      port: 5050
      targetPort: 5050
    - name: "8008"
      nodePort: 31317
      protocol: TCP
      port: 8008
      targetPort: 8008
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: "8800"
      protocol: TCP
      port: 8800
      targetPort: 8800
    - name: "8086"
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: "8083"
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: "2003"
      protocol: TCP
      port: 2003
      targetPort: 2003